### PR TITLE
Se agrego la estructuta basica html y tambien los links para boostrap

### PR DESCRIPTION
**Pull request by Jairo010**
Amigos por favor revisar

### CODE REVIEW

**Comment by FlacoBarona** [comment]
The code that you add is correct, the branch is able to merge :)

**Review by FlacoBarona — APPROVED** [review]

**Review by JosephCargua — APPROVED** [review]
All code is correct

**Review by kend4l — COMMENTED** [review]
it's ok for the merge

**Review by kend4l — APPROVED** [review]
The code is very good

**Pull request merged**
